[versions]
agp = "9.1.0"
kotlin = "2.4.10"
android-minSdk = "29"
android-compileSdk = "37"
android-targetSdk = "37"
lib-version-name = "0.9.0-alpha01"

ienlab-cmp = "3.3.0"

# plugin
compose-plugin = "1.11.1"
compose-material3 = "1.11.0-alpha07"
androidx-compose-tooling = "1.12.0"

# ui
activity-compose = "1.13.0"
lifecycle = "2.11.0"

# backend
core = "1.17.0"
ext-junit = "1.3.0"

vanniktechMavenPublish = "0.37.0"
dokka = "2.2.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

cmp-common = { group = "zone.ien.utils", name = "cmp-common", version.ref = "ienlab-cmp"}
cmp-ui = { group = "zone.ien.utils", name = "cmp-ui", version.ref = "ienlab-cmp"}
cmp-utils = { group = "zone.ien.utils", name = "cmp-utils", version.ref = "ienlab-cmp"}

# ui
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-plugin" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-plugin" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-plugin" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-plugin" }
compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-plugin" }
compose-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-plugin" }

[bundles]
ienlab-cmp = ["cmp-common", "cmp-ui", "cmp-utils"]

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
